---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
spec:
  capacity:
    storage: 1Gi                  # Size of the volume
  accessModes: 
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  namespace: prasad  
spec:
  accessModes:  
    - ReadWriteOnce
  volumeName: nginx-pv
  resources:
    requests:
      storage: 1Gi              # Size of the claim
  storageClassName: ""
...