---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
spec:
  capacity:
    storage: 1Gi                  # Size of the volume
  accessModes: 
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  namespace: prasad  
spec:
  accessModes:  
    - ReadWriteOnce
  volumeName: nginx-pv
  resources:
    requests:
      storage: 1Gi              # Size of the claim
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: prasad  
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html  # Mounting the volume here
              name: nginx-pv-storage  # Persistent volume name should match this
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              cpu: "100m"
              memory: "128Mi"
      volumes:
        - name: nginx-pv-storage  # Declare the volume
          persistentVolumeClaim:
            claimName: nginx-pvc  # Reference to PersistentVolumeClaim
 
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: prasad  # Ensure the namespace matches
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: prasad  # Ensure the namespace matches
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: hello.chaitu.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
